---
title: "Split apply combine ..."
author: "Zahra Khoshmanesh"
topic: "02"
layout: post
root: ../../../
---

In this post, I want to answer the following questions based on the Hadley Wickham paper, "The Split-Apply-Combine Strategy for Data
Analysis" and my experience and underestanding of the subject.

1. **Which (base R) functions do you know that support the split-apply-combine strategy? In your opinion, are these sufficient - state why or why not?**. 
As Hadley Wickham mentioned in the paper, we can use for loop and built in function such as apply and aggregate functions to implement our task, here, map and reduce tasks. However, It needs multiple lines code to perform same thing performed in plyr library just with a few lines. Therefore, plyr library cause to have nicer code that easy to read and underestand and also faster code. In my opinion maybe the built in functions in R and for loops are sufficient for professional people working for many years , yet, they are not efficient and sufficient for beginner having less familiarity with the concept.
2. **Using a dataset of your choice, show (by including the split-apply-combine command(s) in your answer) how you can use the split-apply-combine strategy for a part of the data analysis.**




