---
title: "Split apply combine ..."
author: "Xiyuan Sun"
topic: "02"
layout: post
root: ../../../
---

1. **Which (base R) functions do you know that support the split-apply-combine strategy? In your opinion, are these sufficient - state why or why not?**. 

According to Hadley's paper, in base R, we can tackle this problem with nested loops, or with the apply family of functions. There are some base `R` functions that support the split-apply-combine strategy such as `subset()`, `split()`, `by()`, `apply()`, `sapply()`, `lapply()`, `tapply()`, `aggregate()`, `rbind()`, and `cbind()`. These functions can tackle any task  as `plyr`.

The main disadvantages of the loops is that there is a lot of book-keeping code: the size of the array is hard coded in multiple places and we need to create the output structures before filing them with data. The apply functions simplify the task, but there is not a straightforward way to go from the 2d array of models to the 3d array of residuals. 


2. **Using a dataset of your choice, show (by including the split-apply-combine command(s) in your answer) how you can use the split-apply-combine strategy for a part of the data analysis.**

```{r}
library(plyr)
library(MASS)
library(dplyr)
library(ggplot2)

#make up the data
v1 = c('Yellow','Black','Blue','Red','Yellow','Black','Blue',
        'Red','Yellow','Black','Blue','Red','Yellow','Black',
       'Blue','Red','Blue','Red')

v2 = c(100000,150000,80000,90000,200000,145000,120000,
      300000,250000,200000,160000,90000,90100,150000,
      142000,130000,400000,350000)

v3 = c(100,150,820,920,230,120,70,250,250,110,130,860,980,300,150,170,230,280)

v4 = c('type A','type A','type A','type A','type A','type A','type A',
        'type A','type A','type B','type B','type B','type B','type B',
       'type B','type B','type B','type B')

sales_data<-data.frame(cbind(v1,v2,v3,v4))
colnames(sales_data)<-c("color","sales","transactions","product")
sales_data$sales <- as.numeric(sales_data$sales)
sales_data$transactions <- as.numeric(sales_data$transactions)

print(sales_data)

#step1: split the data into groups based on some criteria (use the column or a combination of columns to split the data into groups)
#group by color
#step2: apply a function to each group independently (aggregate, transform, or filter the data in this step)
#step3: combine the results into a datastructure
sales_data%>%
  group_by(color)%>%
  dplyr::summarize(totalSales = sum(sales),medianTrans=median(transactions),count=n())


```








