---
title: "Split apply combine ..."
author: "Yudi Zhang"
topic: "02"
layout: post
root: ../../../
  ---
  
  ## Background:
  
The `plyr` package has by now been replaced by other, even faster packages, but the idea of *Split, apply, combine* is as relevant as ever.

Read the paper [The Split-Apply-Combine Strategy for Data Analysis](https://www.jstatsoft.org/article/view/v040i01) by Hadley Wickham.


Write a blog post addressing the questions: 
  
1. **Which (base R) functions do you know that support the split-apply-combine strategy? In your opinion, are these sufficient - state why or why not?**. 

  `*apply`, `*bind`, `aggregate`, `split`, `strsplit`, `seperate`, etc. Not sufficient, as mentioned in the paper, those functions are most of the times non readable, and they cannot be well connected with other functions. Somes can be replaced by others in tidyr.
  
2. **Using a dataset of your choice, show (by including the split-apply-combine command(s) in your answer) how you can use the split-apply-combine strategy for a part of the data analysis.**

  If we want to find the average dist for every speed on `cars`.
  
  ```{r}
  # use dplyr
  cars %>% group_by(speed) %>% mutate_at(vars(dist), funs(ave_dist = mean(.)*speed))
  # But I think aggregate cannot do this by group
  aggregate(cars$dist, by = list(cars$speed), FUN = function(x) mean(x)*cars$speed)
  ```
