---
title: "Blog #3: Ethics and Reproducibility..."
author: "Brianna Lawton"
topic: "03"
layout: post
root: ../../../
---

## Prompt:


In May 2015 Science retracted - without consent of the lead author - a paper on  how canvassers can sway people's opinions about gay marriage, 
see also: http://www.sciencemag.org/news/2015/05/science-retracts-gay-marriage-paper-without-agreement-lead-author-lacour
The Science Editor-in-Chief cited as reasons for the retraction that the original survey data was not made available for independent reproduction of results, that survey incentives were misrepresented and that statements made about sponsorships turned out to be incorrect.<br>
The investigation resulting in the retraction was triggered by two  Berkeley grad students who attempted to replicate the study and discovered that the data must have been faked.
 
[FiveThirtyEight](https://fivethirtyeight.com/features/how-two-grad-students-uncovered-michael-lacour-fraud-and-a-way-to-change-opinions-on-transgender-rights/) has published an article with more details on the two Berkeley students' work.

Malicious changes to the data such as in the LaCour case are hard to prevent, but more rigorous checks should be built into the scientific publishing system. All too often papers have to be retracted for unintended reasons. [Retraction Watch](https://retractionwatch.com/) is a data base that keeps track of retracted papers (see the related [Science magazine](https://www.sciencemag.org/news/2018/10/what-massive-database-retracted-papers-reveals-about-science-publishing-s-death-penalty) publication). 

Read the paper [Ten Simple Rules for Reproducible Computational Research](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285) by Sandve et al.


Write a blog post addressing the questions: 

1. **Pick one of the papers Retraction Watch features on their website and describe what went wrong**. 

## Q1 Response

The Center for Disease Control (CDC) retracted a 2016 paper on suicide due to errors in the paper concerning the miscategorization of the occupation "farmer" which skewed results due to errors in the analysis.   
The CDC's initial article published, "Suicide Rates by Occupational Group - 17 States, 2012" claimed that farmers were at particularly high risk of suicide. This result raised issue with a website called "The New Food Economy (TNFE)" due to what they said was "the misclassification of farmer suicides in a way that significantly inflated the rate of these events." TNFE mentioned that they had raised concerns about the error early before.
The issue arose due to the discrepency of what a "farmer" occupation was considered versus an individual who "works in agriculture."

The CDC investigated the study and after reaching a complete analysis, decided to retract the original report because the corrections changed the conclusions. One of the main corrected errors was the manual misclassification of some occupation codes in the earlier report (e.g., erroneous coding of farmers to the Farming, Fishing, and Forestry major occupational group instead of to the correct Management major occupational group), which led to errors in reporting of suicide numbers and rates in some groups.

This incident of retraction helped the CDC look into other papers/articles that could have misrepresented data and drawn false or skewed conclusions.

Referenced: Retraction Watch, "In a first, U.S. CDC retracts, replaces study about suicide risk in farmers"
https://retractionwatch.com/2018/11/15/in-a-first-u-s-cdc-retracts-replaces-study-about-suicide-risk-in-farmers/ 
Link to retracted article: https://www.cdc.gov/mmwr/volumes/65/wr/mm6525a1.htm


2. **After reading the paper by Sandve et al. describe which rule you are most likely to follow and why, and which rule you find the hardest to follow and will likely not follow in your future projects.**

## Q2 Response

After reading the paper, "Ten Simple Rules for Reproducible Computational Research" by Sandve et al., I am most likely to follow rule # X because


After reading the paper, I find rule # X probably the hardest to follow (and will likely not follow) for future projects because  





## Instructions:

Update your forked version of the 'blog-2019' repository (or re-fork it after deleting your previous repo).

Save a **copy** of this file, replacing "Lastname" and "Firstname" with your own and *leave the original unedited*.

In **your copy**, replace the `title:` and `author:` fields in the YAML above, while leaving the remaining fields intact. Remove the background and the instructions sections and write your blog post! 

Once you are done, **create a pull request** to upload your changes to the original repository. Do not commit the compiled HTML file to the repository.
