---
title: "Ethics and Reproducibility..."
author: "Zahra Khoshmanesh"
topic: "03"
layout: post
root: ../../../
---

1. **Pick one of the papers Retraction Watch features on their website and describe what went wrong**. 
I picked “Primary Prevention of Cardiovascular Disease with a Mediterranean Diet,” which has been cited 1,759 times, according to
Clarivate Analytics’ Web of Science. This paper provided some proof that the Mediterranean diet can directly prevent heart attacks,
stroke, and other cardiovascular problems. The author replaced old paper with newer one in such a way that the finding is softer in it.
the New England Journal of Medicine retracted the paper because of problems in the way the study was done.In the original paper they
claimed that Mediterranean diet directly cause to have fewer heart attack. However in new version of article the author changed the claim
that people eating the Mediterranean diet had fewer strokes and heart attacks.



2. **After reading the paper by Sandve et al. describe which rule you are most likely to follow and why, and which rule you find the hardest to follow and will likely not follow in your future projects.**


