---
title: "A Series of Tubes..."
author: "Zahra Khoshmanesh"
topic: "09"
layout: post
root: ../../../
output: 
  html_document: 
    css: extra.css
---


1. The `xml2` R package can be used to work with xml files. Write a function, `current_weather` that accepts a 4-letter airport code (KAMW in the URL here: https://w1.weather.gov/xml/current_obs/KAMW.xml) and returns a data frame with the airport location (station ID, latitude, longitude), last update time, and current weather information (temperature, weather condition, wind speed and direction) at that airport. The `xml2` functions `read_xml`, `xml_children`, `xml_name`, and `xml_text` will be useful. Remember to handle errors and check inputs, and make sure to return a data frame with appropriate data types. 

2. Which HTML tags did you investigate? Describe how to format at least 3 separate pieces of a document using HTML tags.

3. Compile this Rmarkdown document to HTML, then open the HTML file in a web browser. Open the inspector console for your browser (Ctrl-Shift-I in Chrome, Ctrl-Shift-C in Firefox) and look at the HTML code corresponding to various parts of the document. <br>
Answer the following questions:
    - What types of tags did you find? 
    - How are code chunks formatted in HTML?
    - What differences are there in the HTML markup for R code chunks and R output blocks?
    
4. In R, the `rvest` package, which is part of the tidyverse, makes it (relatively) easy to pull specific pieces from structured documents. The `html_nodes` function selects nodes using either xpath or css, and additional functions such as `html_attrs`, `html_text`, and `html_table` pull information out of the markup text.<br>
Choose a Wikipedia page that has at least one image to test the `rvest` package out

```{r}
library(rvest)
spring <- read_html("https://en.wikipedia.org/wiki/Spring_(season)")

html_node(spring,"img") %>% 
  xml_attr(attr="src") %>%
  paste0("https:",.) %>%
  magick::image_read()
```
