---
title: "Blog1 Post"
author: "Qing He"
topic: "01"
layout: post
root: ../../../
---

## Background:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from [http://happygitwithr.com/](http://happygitwithr.com/). Have a look over the index and pick one of the chapters for a more in-depth read.

Write a blog post answering the following questions: 

1. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 

The biggest mishap was that it was difficult to check the team members progress, which makes it difficult to control the project progress. The git can make the cooperation of coding easier and much more efficient by avoiding sending codes to collaborators back and forth through cloud or email, and it can be synced while coding, which will make the coding progress more transparent to team members. 


2. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.
Github is new to me. The way github sync files are efficient since it can be done during the coding. Moreover, new files will not override the previous files, all changes are stored and easily pulled out for future self.

## Instructions:

Fork the 'blog-2019' repository 

Save a **copy** of this file, replacing "Lastname" and "Firstname" with your own and *leave the original unedited*.

In **your copy**, replace the `title:` and `author:` fields in the YAML above, while leaving the remaining fields intact. Remove the background and the instructions sections and write your blog post! 

Once you are done, **create a pull request** to upload your changes to the original repository. Do not commit the compiled HTML file to the repository.
