---
title: "First blog 1/15"
author: "Jing Li"
topic: "01"
layout: post
root: ../../../
---

## Background:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from http://happygitwithr.com/. Have a look over the index and pick one of the chapters for a more in-depth read.

Write a blog post answering the following questions: 

1. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 

One of my lab project, there are four lab members involved in. The biggest mishap is that we have lots of sctipts, and the scripts revised by different people frequently. Git helps us to update and trace the change of the scripts, and also provide us the history of all versions.

2. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.

I got the new feature 12. connect Rstusio to git and github. I didn't know that Rstudio could make change on the git files directly. I just used shell push and pull files to github. It's more convinient for me to modify the R file directly in Rstudio.